// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCAs0FNYHVdCJAR7fH8DOk8pHQ9zlRlY',
    appId: '1:949463670257:web:3dcfd65ff60f1bc009f850',
    messagingSenderId: '949463670257',
    projectId: 'project-39f5b',
    authDomain: 'project-39f5b.firebaseapp.com',
    storageBucket: 'project-39f5b.firebasestorage.app',
    measurementId: 'G-90TVG0LS6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WqJWff-QggpixXBmZ5djiPNQLYfg03c',
    appId: '1:949463670257:android:8c4aa9a3921cd77909f850',
    messagingSenderId: '949463670257',
    projectId: 'project-39f5b',
    storageBucket: 'project-39f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBx0KymeSZOaCzbDsXAleC-er2-RjhQ0',
    appId: '1:949463670257:ios:2f7e7a0c45036b3409f850',
    messagingSenderId: '949463670257',
    projectId: 'project-39f5b',
    storageBucket: 'project-39f5b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBx0KymeSZOaCzbDsXAleC-er2-RjhQ0',
    appId: '1:949463670257:ios:2f7e7a0c45036b3409f850',
    messagingSenderId: '949463670257',
    projectId: 'project-39f5b',
    storageBucket: 'project-39f5b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCAs0FNYHVdCJAR7fH8DOk8pHQ9zlRlY',
    appId: '1:949463670257:web:dfd8d93b5934ee7609f850',
    messagingSenderId: '949463670257',
    projectId: 'project-39f5b',
    authDomain: 'project-39f5b.firebaseapp.com',
    storageBucket: 'project-39f5b.firebasestorage.app',
    measurementId: 'G-14VK5MP0G7',
  );

}