// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2O7Yzlp3k0xJ5Oqnm6oUvX5vOqZUcG24',
    appId: '1:441893151420:web:6e383a3f2ad8fdd4fc66b9',
    messagingSenderId: '441893151420',
    projectId: 'college-project-77e42',
    authDomain: 'college-project-77e42.firebaseapp.com',
    storageBucket: 'college-project-77e42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALu-vC_uIF0blFU5JQvEvirBeto6yo4ds',
    appId: '1:441893151420:android:63433a2ea2a949dbfc66b9',
    messagingSenderId: '441893151420',
    projectId: 'college-project-77e42',
    storageBucket: 'college-project-77e42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOrdE5ucYSy5ZthFpW2SiOj3oyoe9WOzg',
    appId: '1:441893151420:ios:13087d20ab471db7fc66b9',
    messagingSenderId: '441893151420',
    projectId: 'college-project-77e42',
    storageBucket: 'college-project-77e42.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOrdE5ucYSy5ZthFpW2SiOj3oyoe9WOzg',
    appId: '1:441893151420:ios:13087d20ab471db7fc66b9',
    messagingSenderId: '441893151420',
    projectId: 'college-project-77e42',
    storageBucket: 'college-project-77e42.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2O7Yzlp3k0xJ5Oqnm6oUvX5vOqZUcG24',
    appId: '1:441893151420:web:987be92344cef857fc66b9',
    messagingSenderId: '441893151420',
    projectId: 'college-project-77e42',
    authDomain: 'college-project-77e42.firebaseapp.com',
    storageBucket: 'college-project-77e42.firebasestorage.app',
  );

}